### ISSUE TITLE
Add support for scouting using DreamFes rates?

### ISSUE THREAD

**Issue by dburr** [DamourYouKnow/HAHA-NO-4STAR#6]
subject line says it all... handling DF-exclusive cards and rate ups is probably too much of a pain (and I wouldn't blame you at all if you decided not to do this) but being able to scout using the base DF rates (6% 4star, etc.) would be pretty sweet. Something like adding a `dreamfes` (or `df`) argument to the `$play10` command. e.g. `$play10 dreamfes` or `$play10 popipa df`

**Comment by DamourYouKnow** [comment]
Implemented two new commands, `$playdf` and `$playdf10`.
